cleanup domain check/logic, and unnecessary debugging output

diff --git a/sud b/sud
--- a/sud
+++ b/sud
@@ -23,15 +23,17 @@ ipregex='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
 if [[ $node =~ ^$ipregex\.$ipregex\.$ipregex\.$ipregex$ ]]; then
   DNScheck $node || "will use $node address, but no reverse DNS is setup"
 else
-  if DNScheck $node.$yourDomain ; then
-    echo found $node.$yourDomain
-    node=$node.$yourDomain
-  else
-    echo could not resolve $node.$yourDomain, trying $node
-    if DNScheck $node ; then
-      echo found $node
-    else
+  if [[ "$node" == *$yourDomain ]] ; then
+    if ! DNScheck $node ; then
       echo "unable to resolve $node" && exit 1
+    fi
+  else
+    if DNScheck $node.$yourDomain ; then
+      node=$node.$yourDomain
+    else
+      if ! DNScheck $node ; then
+        echo "unable to resolve $node" && exit 1
+      fi
     fi
   fi
 fi
